### ISSUE TITLE
Plugin installation error breaking sprout-vim cookbook build

### ISSUE THREAD

**Issue by aramprice** [pivotal/vim-config#5]
See https://travis-ci.org/pivotal-sprout/sprout-vim/builds/136839029

Potential culprit:

```
Error detected while processing /Users/travis/.vim/bundle/j-split/plugin/j-spli
```

**Comment by nertzy** [comment]
Those warnings are (unfortunately) normal. The problem is that some of the plugins we include don't play well with getting loaded after the Vundle installation process. It's a sort of chicken-and-egg problem since Vundle runs within Vim and also modifies the vim-config.

If anyone knows a way to either send <kbd>Return</kbd> once Vundle finishes, or to silence its warnings, then installing things in an automated fashion will be much easier.

**Comment by aramprice** [comment]
I don't have enough experience with vim to contribute much but perhaps @luan has some tips?

**Comment by nertzy** [comment]
I just fixed it by forking the plugins that had problems and improving the install script to be non-blocking. I triggered a rebuild of sprout-vim at https://travis-ci.org/pivotal-sprout/sprout-vim/builds/136845025 so let's see how that turns out. Should be better overall!

**Comment by nertzy** [comment]
See 48ab11862e4841ef33db0d6b883660522aca2fd0...31a8e091739a8b7da64d73fdfb5228b90794631a for more details.

**Comment by aramprice** [comment]
@nertzy - it looks like that got us past the error updating the vim plugins, thanks!

**Comment by aramprice** [comment]
Feel free to close
